### ISSUE TITLE
Create docs with current architecture and dependencies

### ISSUE THREAD

**Issue by rafalgajos** [bkomorniczak/glowing-octo-guide#3]

**Comment by rafalgajos** [comment]
### Przegląd Architektury

Projekt AIMobs to mod do Minecrafta, opracowany w języku Java, specjalnie dla loadera modów Fabric. Oto przegląd jego architektury i zależności na podstawie kluczowych plików przeanalizowanych z repozytorium:

#### Architektura

1. **Główna Klasa Moda (`AIMobsMod.java`)**: 
   - Inicjalizuje moda i ustawia rejestrację poleceń oraz wywołania zwrotne ataku na jednostki.
   - [AIMobsMod.java](https://github.com/rebane2001/aimobs/blob/mane/src/main/java/com/rebane2001/aimobs/AIMobsMod.java)

2. **Obsługa Poleceń (`AIMobsCommand.java`)**: 
   - Definiuje polecenia dla moda, takie jak włączanie/wyłączanie moda, ustawianie kluczy API i dostosowywanie ustawień.
   - [AIMobsCommand.java](https://github.com/rebane2001/aimobs/blob/mane/src/main/java/com/rebane2001/aimobs/AIMobsCommand.java)

3. **Zarządzanie Konfiguracją (`AIMobsConfig.java`)**: 
   - Zarządza ustawieniami konfiguracyjnymi moda, w tym kluczami API i ustawieniami moda.
   - [AIMobsConfig.java](https://github.com/rebane2001/aimobs/blob/mane/src/main/java/com/rebane2001/aimobs/AIMobsConfig.java)

4. **Obsługa Działań (`ActionHandler.java`)**: 
   - Obsługuje interakcje z jednostkami, takie jak rozpoczynanie rozmów i reagowanie na działania jednostek.
   - [ActionHandler.java](https://github.com/rebane2001/aimobs/blob/mane/src/main/java/com/rebane2001/aimobs/ActionHandler.java)

5. **Obsługa Żądań (`RequestHandler.java`)**: 
   - Zarządza żądaniami do usługi AI (prawdopodobnie OpenAI) w celu generowania odpowiedzi.
   - [RequestHandler.java](https://github.com/rebane2001/aimobs/blob/mane/src/main/java/com/rebane2001/aimobs/RequestHandler.java)

6. **Mixiny**:
   - Modyfikują lub rozszerzają istniejące klasy Minecrafta. Na przykład `ChatHudAccessor` i `ClientPlayNetworkHandler` są używane do integracji funkcjonalności moda z obsługą czatu i sieci w Minecraft.
   - [ChatHudAccessor.java](https://github.com/rebane2001/aimobs/blob/mane/src/main/java/com/rebane2001/aimobs/mixin/ChatHudAccessor.java)
   - [ClientPlayNetworkHandler.java](https://github.com/rebane2001/aimobs/blob/mane/src/main/java/com/rebane2001/aimobs/mixin/ClientPlayNetworkHandler.java)

7. **Pliki Zasobów**:
   - Zawierają metadane moda (`fabric.mod.json`) i konfiguracje mixina (`aimobs.mixins.json`).
   - [fabric.mod.json](https://github.com/rebane2001/aimobs/blob/mane/src/main/resources/fabric.mod.json)
   - [aimobs.mixins.json](https://github.com/rebane2001/aimobs/blob/mane/src/main/resources/aimobs.mixins.json)

#### Zależności

- **Fabric API**: Używany jako zestaw narzędzi do modowania Minecrafta.
- **Wersja Minecrafta**: Przeznaczony dla Minecrafta 1.19.4.
- **Wersja Java**: Projekt jest skonfigurowany do użycia Java 17.
- **Gradle**: Wykorzystywany do automatyzacji budowy i zarządzania zależnościami.
- **GSON**: Do obsługi JSON w zarządzaniu konfiguracją.
- **SLF4J**: Do logowania w modzie.

Szczegółowe informacje o zależnościach można znaleźć w plikach `build.gradle` i `gradle.properties`:
- [build.gradle](https://github.com/rebane2001/aimobs/blob/mane/build.gradle)
- [gradle.properties](https://github.com/rebane2001/aimobs/blob/mane/gradle.properties)

---

**Comment by bkomorniczak** [comment]
Linki zwracają 404.

**Comment by rafalgajos** [comment]
@bkomorniczak dzięki nie zauważyłem literówki w hiperłączach 👍 linki już działają
